import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'

const Home: NextPage = () => {
  type ArticleType = {
    article: {
      title: string
      subTitle: string
      bodyText: string
    }[]
  }
  const [data, setData] = useState<ArticleType>()
  useEffect(() => {
    const init = async () => {
      const result = await fetch('http://localhost:3002/api/test')
      if (result) {
        const data = (await result.json()) as ArticleType
        setData(data)
      }
    }
    init()
  })
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold m-4">Hello world!</h1>
        <div className="mt-10 mx-4">
          {data ? (
            data.article.map((article, index) => (
              <div className="pb-3" key={`article_${index}`}>
                <h2 className="text-2xl">{article.title}</h2>
                <h3 className="text-xl">{article.subTitle}</h3>
                <div>{article.bodyText}</div>
              </div>
            ))
          ) : (
            <></>
          )}
        </div>
      </main>
    </div>
  )
}

export default Home
